### ISSUE TITLE
On-screen keyboard for touchscreen

### ISSUE THREAD

**Issue by Scorpion2185** [i3/i3lock#325] opened 2022-08-23 07:49 UTC
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
No on-screen keyboard, it can be useful for tablet PC/phone users, as well as
 for mobility impaired users.

## Expected Behavior
I'd like to have an option to have some OSK, to unlock i3lock.
It could also switch tty eventually.

**Comment by stapelberg** [comment] 2022-08-23 15:37
duplicate of https://github.com/i3/i3lock/issues/273, which contains a working solution

**Closed by stapelberg** 2022-08-23 15:37 UTC
