### ISSUE TITLE
i3lock crashes if dmenu was opened before locking

### ISSUE THREAD

**Issue by adnidor** [i3/i3lock#67] opened 2016-04-06 16:46 UTC
Duplicate in i3 repo from november, never reported here and not fixed:  i3/i3#2057

Steps to reproduce:
`dmenu_run; sleep 1; ./i3lock`

Expected Result: i3lock displaying over dmenu and locking the screen

Actual Result: i3lock displaying under dmenu and crashing after about one second

Tested with  2.7-9-g59705b0 (2015-12-25) and 2.7 (2015-05-20)

**Comment by Airblader** [comment] 2016-04-06 16:49
This is because dmenu grabs the keyboard and in turns i3lock can't. Unfortunately this is just how X works and there is virtually nothing we can do (in fact, we already do what is generally recommended: try for a while and then give up).

We already have a ticket, #36, to provide visual indication to the user. It's really all we can do.

closing as a duplicate of #35

**Closed by Airblader** 2016-04-06 16:49 UTC

**Comment by 8carlosf** [comment] 2016-04-06 17:44
May I suggest that you can make a script that closes dmenu if running and then calls i3lock.

**Comment by Airblader** [comment] 2016-04-06 17:46
That works for dmenu, but any application could grab the keyboard or pointer.
