### ISSUE TITLE
Feature request: Set colors for unlock indicator

### ISSUE THREAD

**Issue by mrjovanovic** [i3/i3lock#34] opened 2015-09-18 00:21 UTC
Generally I really appreciate the simplicity of i3lock, so I'm sorry to ask for another feature. That said, there is a Windows pointer. :)

Title is self explanatory. [This fork](https://github.com/eBrnd/i3lock-color) does it like so:
```
--insidevercolor=rrggbbaa -- Inside of the circle while the password is being verified
--insidewrongcolor=rrggbbaa -- Inside of the circle when a wrong password was entered
--insidecolor=rrggbbaa -- Inside of the circle while typing/idle
--ringvercolor=rrggbbaa -- Outer ring while the password is being
```
For the purposes of visual matching, but also to make the unlock indicator actually useful for people with protanopia, deuteranopia, etc. (red-green color blindness).

**Comment by stapelberg** [comment] 2015-09-18 06:47
duplicate of #15, we don’t want to make the unlock indicator customizable

> For the purposes of visual matching, but also to make the unlock indicator actually useful for people with protanopia, deuteranopia, etc. (red-green color blindness).

If this is really an issue and you know how to fix it, I’m happy to accept a pull request which changes the colors to be more useful.

**Closed by stapelberg** 2015-09-18 06:47 UTC
