### ISSUE TITLE
Indication of a keyboard layout

### ISSUE THREAD

**Issue by viocost** [i3/i3lock#294] opened 2020-12-28 06:27 UTC
## I'm submitting a…

<pre>
[ ] Bug
[X ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

There is no indication of the current keyboard layout, 
so user has to type password times and times until the correct keyboard layout is guessed.

## Expected Behavior

There must be visible indication of current keyboard layout on the lock screen, like Keyboard: Ru 

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 
</pre>

**Comment by stapelberg** [comment] 2020-12-28 21:22
This is a duplicate of https://github.com/i3/i3lock/issues/287

**Closed by stapelberg** 2020-12-28 21:22 UTC
