### ISSUE TITLE
Allow passing shortcuts to WM

### ISSUE THREAD

**Issue by Ceda-EI** [i3/i3lock#209] opened 2018-12-03 10:32 UTC
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Other (Please describe in detail)
</pre>

Allow passing certain shortcuts to the WM so that shortcuts pressed in i3lock should be handled by the WM. The list should be configurable. Possible use cases are controlling music from lock screen, changing volume, brightness, etc

**Comment by Airblader** [comment] 2018-12-03 10:39
This is essentially a duplicate of #52

**Closed by Airblader** 2018-12-03 10:39 UTC
