### ISSUE TITLE
-i ignored sometimes without an error

### ISSUE THREAD

**Issue by nic-hartley** [i3/i3lock#265] opened 2020-03-04 17:02 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Calling `i3lock -i /path/to/image.png` displays a white screen instead of the image.
The image is the correct size (another image with the same dimensions loads as expected) and far smaller on disk than the correctly-loaded one, so it's not running out of memory.
`feh` can load it, so I assume it's a valid PNG.
No obviously image-related errors are outputted with `--debug`, but I do have a lot of X11 errors, of the form `X11 Error received! sequence 0xcd, error_code = 2`. The sequence number increments, and the error codes are:

- 3896x error code 9
- 190x error code 143
- 95x error code 2
- 95x error code 4

The exact numbers change depending on how long I let i3lock run, keys entered, wrong passwords, etc., but the proportions are always roughly the same.

## Expected Behavior
I want to see my lock screen image instead of a white screen, or at least an error that actually describes what's going wrong instead of silently ignoring `-i`.

## Reproduction Instructions
[This](https://i.imgur.com/VUlFbMC.png) is one image which fails to load.
This is a command to generate them (nothing output by this command has worked yet, calling `i3lock -i /tmp/lock.png`):

```
convert -size 640x216 pattern:gray100 +noise random -brightness-contrast -25x-50 -filter point -resize 6400x2160 /tmp/lock.png
```

(Adjust the `-resize XXxYY` argument according to your total screen size)

[Here's](https://i.imgur.com/FMCUFxO.jpg) an image which works.

## Environment
Output of `i3lock --version`: `i3lock: version 2.12 © 2010 Michael Stapelberg`.
`pacman` reports no newer version available.

**Comment by stapelberg** [comment] 2020-03-04 21:34
This sounds like a duplicate of #244, i.e. using 16bpc images is currently broking due to a cairo bug.

**Closed by stapelberg** 2020-03-04 21:34 UTC

**Comment by nic-hartley** [comment] 2020-03-04 22:28
Ah, cool, that's probably it. Not something I'd have noticed. Thanks!
