### ISSUE TITLE
[i3lock feature] Display current keyboard layout on password prompt.

### ISSUE THREAD

**Issue by taras-ko** [i3/i3lock#82] opened 2016-06-22 12:11 UTC
I have three layouts on my desktop. Two of them have cyrillic symbols (RU, UA). Also I have a really complicated password in English. So for me it's very confusing to guess "What is the current layout when I'm typing unlock password?". I know at least one more person who has the same issues as I.

Thanks.

**Comment by Airblader** [comment] 2016-06-22 12:13
Duplicate of https://github.com/i3/i3lock/issues/56. Please use a wrapper script around i3lock to set your preferred layout for typing your password.

**Closed by Airblader** 2016-06-22 12:13 UTC

**Comment by taras-ko** [comment] 2016-06-22 12:15
Sorry, thank you!

**Comment by Mikaela** [comment] 2019-02-18 22:34
Does anyone have an example of a layout specifying wrapper script? I have three layouts configured luckily of which two enter the password correctly, but the third is a bit strange (`ŝĝertŭuiopĵ.asdfghjkl,zĉcvbnm`).

**Comment by krey** [comment] 2021-01-04 15:57
The easiest solution is to switch over to [i3lock-color](https://github.com/Raymo111/i3lock-color). It's basically the same as i3lock with additional features. Run `i3lock-color --keylayout 1`. Example: https://github.com/Raymo111/i3lock-color/issues/186#issuecomment-750661363

**Comment by Raymo111** [comment] 2021-01-26 00:07
> The easiest solution is to switch over to [i3lock-color](https://github.com/Raymo111/i3lock-color). It's basically the same as i3lock with additional features. Run `i3lock-color --keylayout 1`. Example: [Raymo111#186 (comment)](https://github.com/Raymo111/i3lock-color/issues/186#issuecomment-750661363)
^^ I wholly endorse this comment. Personally I think i3lock is great, but it has a limited set of features, hence why I maintain the more "extravagant" fork.
