### ISSUE TITLE
Trying to read (valid) png image from stdin causes "out of memory"

### ISSUE THREAD

**Issue by SoptikHa2** [i3/i3lock#284] opened 2020-08-03 09:05 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When the image is read from `/dev/stdin` or `/proc/self/fd/0`, an "out of memory" error is displayed every time.

## Expected Behavior
The image is read from stdin successfully. 

## Reproduction Instructions
I tried to take an image, resize it, and send it to i3lock:
```sh
convert -resize $(xrandr -q | grep -Eo '[0-9]+x[0-9]+' -m 1 | cut -dx -f1) ~/archlinux-dotfiles/lockscreen.png - | i3lock -i /dev/stdin -ue
Could not load image "/dev/stdin": out of memory
convert -resize $(xrandr -q | grep -Eo '[0-9]+x[0-9]+' -m 1 | cut -dx -f1) ~/archlinux-dotfiles/lockscreen.png - | i3lock -i /proc/self/fd/0 -ue
Could not load image "/proc/self/fd/0": out of memory
```
Writing it to tmp and then reading it works like expected:
```sh
convert -resize $(xrandr -q | grep -Eo '[0-9]+x[0-9]+' -m 1 | cut -dx -f1) ~/archlinux-dotfiles/lockscreen.png /tmp/img.png && i3lock -i /tmp/img.png -ue
```

The image I used is [here](https://github.com/SoptikHa2/archlinux-dotfiles/blob/master/lockscreen.png).

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: version 2.12
</pre>

**Comment by stapelberg** [comment] 2020-08-03 09:07
This is a duplicate of https://github.com/i3/i3lock/issues/227

**Closed by stapelberg** 2020-08-03 09:07 UTC
