### ISSUE TITLE
Unlocking i3lock via fingerprint only, when fingerprint active?

### ISSUE THREAD

**Issue by opusz** [i3/i3lock#276] opened 2020-06-29 13:14 UTC
Hello everyone,
I am a i3 newbie and use it since a few weeks. i3 seems to be awesome 'cause of <insert several awesomeness here>
...but I have a little problem with i3lock. I use a fingerprint authentication and at least in the login screen it's possible to use the fingerprint but typing a password is also possible. In i3lock it is not...?
What do i wrong?

## I'm submitting a…

<pre>
[?] Bug
[ ] Feature Request
[X] Other (Please describe in detail)
</pre>

## Current Behavior

The behaviour unlock via fingerprint: Green circle in the middle, typing return key shows "verifing...", and unlocking via fingerprint is possible and works (but not before typing return)

The behaviour unlock via password(?): Green circle in the middle, typing any key (password) shows light green parts at the border of the circle (I guess that's the visual feedback for a typing key?), and then.... typing return activates the fingerprint mechanism ("verifying...") and a can unlock via fingerprint only...

## Expected Behavior

Type password and press enter -> start verifying typed password
Type enter without password -> start verifying via fingerprint
...or something similar... I just wanna have the choice every time

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 
i3lock: version 2.12.c.4-12-gb5724ab (2020-06-19) © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li
</pre>

**Comment by Airblader** [comment] 2020-06-29 13:19
duplicate of #217

**Closed by Airblader** 2020-06-29 13:19 UTC
