### ISSUE TITLE
Impossible to switch off ibus-ime when screen is locked

### ISSUE THREAD

**Issue by smhaziq** [i3/i3lock#78] opened 2016-05-25 23:05 UTC
Description
----------------
I use ibus Arabic ime (m17n) and when I enter the lock screen, there is no way to switch back to english input method so it's impossible for me to input correct password. In order to fix this, I switch to another tty and disable i3lock on start up and reboot.

Steps to Reproduce
----------------
1. activate ibus ime (non english input method .. say arabic ime for example)
2. lock the screen 
3. impossible to turn off arabic ime from locked screen ( so: cannot input correct password)

Expected Results
----------------
shortcut to switch ime should work.
or ime should be disabled completely for locked screen.

**Comment by Airblader** [comment] 2016-05-25 23:20
Duplicate of #52, #69, #55 

This has been discussed multiple times in the past. We can't allow specific bindings to go through for security reasons but also don't want the complexity of layout switching in i3lock itself because it increases risks.

Just wrap your i3status call with a command that resets your keyboard layout to the layout you want to use for entering a password.

**Closed by Airblader** 2016-05-25 23:20 UTC
