### ISSUE TITLE
Please add functional for show layers (en,ru and etc)

### ISSUE THREAD

**Issue by oditynet** [i3/i3lock#338] opened 2023-03-30 08:10 UTC
<pre>
[ ] Bug
[X] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I want see a layers of keyboard then write a password (en , ru , etc.) and indicated about press CAPSLOCK

**Comment by stapelberg** [comment] 2023-03-30 08:13
duplicate of https://github.com/i3/i3lock/issues/287

**Closed by stapelberg** 2023-03-30 08:13 UTC

**Comment by oditynet** [comment] 2023-03-30 10:16
Dear stapelberg. Please, show my commit about duble.
https://github.com/i3/i3lock/issues/287#issuecomment-1489976496
