### ISSUE TITLE
i3lock extremely slow after latest update

### ISSUE THREAD

**Issue by skmexyz** [i3/i3lock#128] opened 2017-05-28 23:14 UTC
I am using i3lock (version: 2.9-1~~xenial1) from the http://debian.sur5r.net/i3 repo and it appears to be extremely slow after the latest update (I've rebooted just to be sure). I am using it on Ubuntu 16.04.

it's slow:

1. When locking (there's an additional second or so of delay)
2. When unlocking - there's a delay between when you press a key & when the circle lights up to acknowledge that a key has been pressed. (as in, I'm guessing it accepts the keys at the normal pace, but there's a considerable delay displaying it on screen).

**Comment by mid-kid** [comment] 2017-05-29 18:39
Quick guess: It might be this commit: https://github.com/i3/i3lock/commit/80d4452ec680bcb0e57418f69d44d88ded82047c
Try applying this patch, which reverts the commit: http://chunk.io/f/de3c2b9b70a24e3e9af160d2263c5486.patch

**Comment by chrjguill** [comment] 2017-05-31 00:11
There's been a couple of people who've poked on my fork's issues about compositors, so I guess I'll chime in here (maybe I should make a separate issue? Not sure if these should fall under this or not).

A few people are having problems with compositors not properly dealing with i3lock in a few ways - sometimes the compositor doesn't clean up after i3lock or something, and sometimes compositors cause flickering and stuff in i3lock.

All of their issues have been present in [xsecurelock](https://github.com/google/xsecurelock), so whatever's going on, it's probably something wholly with the compositor, and not a locking program.

Personally, I've had no issues using compton (with a fairly minimal config): i3lock works fine on top of it, notifications don't show up, and there's no graphical issues during or after. Apparently that's not the case across the board, though.

I've put a `--no-composite` argument into my fork for now (see https://github.com/chrjguill/i3lock-color/commit/d9f2e04bab3c5f2bed674edd085355da255f892b); I don't think it's good enough to go into upstream i3lock, though, since it just feels... hacky.

**Comment by mid-kid** [comment] 2017-05-31 11:28
I've been messing with my compton config, and I've noticed that the cause for this problem is compton's fading option. When that's disabled, the screen is properly blanked. However, even with a completely "clean" compton config, the X process starts using a bunch of CPU, and there's the input lag.
Like @chrjguill said, though, I'm sure it's a problem with the compositor, not so much the locker.

**Comment by stapelberg** [comment] 2017-06-12 08:40
@sandsmark Is this issue related to your https://github.com/i3/i3lock/pull/96?

**Comment by Fandekasp** [comment] 2017-06-14 04:41
Same issue for me these past days... takes up to 6 seconds before removing the lock screen

**Comment by sandsmark** [comment] 2017-06-17 18:17
what compositors, versions of the compositors, and mesa drivers do you all use?

**Comment by mid-kid** [comment] 2017-06-18 20:12
@sandsmark 
compton-git-316eac0 (2017-04-30)
xf86-video-intel-git_20160601_b617f80
mesa-11.2.2
I might need updates on some of these, but that's what I use.

**Comment by julianbrost** [comment] 2017-06-18 20:16
The same problem happens with xcompmgr.

Versions:
xcompmgr 1.1.7-2
mesa 17.1.2-1
xf86-video-intel 2.99.917+777+g6babcf15-1

**Comment by jdkbx** [comment] 2017-06-20 08:31
Same here, xcompmgr 1.1.7, mesa 17.1.2, xorg-drivers 1.19 (modesetting ddx on intel).

**Comment by Airblader** [comment] 2017-06-20 08:35
Can anyone here please test again with the current HEAD? We just merged the reversal of #96 and I assume this fixes it.

**Comment by jdkbx** [comment] 2017-06-20 08:43
Looks good. Snappy as ever. Thanks.

**Comment by Airblader** [comment] 2017-06-20 08:50
Thanks for the feedback!

**Closed by Airblader** 2017-06-20 08:50 UTC

**Comment by nabice** [comment] 2017-06-26 08:49
Works now!

**Comment by hossbeast** [comment] 2017-07-16 00:37
still super slow for me, built from 3009ab422d136b8aefda080f585e51cd8d93b7fd

**Comment by Airblader** [comment] 2017-07-16 07:48
@hossbeast In that case please open a new issue and bisect where the problem starts.

**Comment by boydthomson** [comment] 2017-11-13 19:16
I'm having this issue on Ubuntu 17.10 with i3-gaps.  Not sure where to go from here...
