### ISSUE TITLE
i3lock stuck on "verifying" after suspend

### ISSUE THREAD

**Issue by SinForest** [i3/i3lock#131] opened 2017-06-12 16:23 UTC
I'm using i3lock 2.9-1 from the official ARCH repos.
When I lock the laptop, keep in on suspend for a while and try unlocking it, the unlocking freezes at "verifying...".
I can switch to other TTYs.
The error does not occur when downgrading to version 2.8-1.
I'm using i3lock -efi <IMAGE>.

**Comment by Airblader** [comment] 2017-06-12 17:09
Van you perhaps bisect the issue since it works with 2.8?

**Comment by maximbaz** [comment] 2017-06-13 08:03
I experience this as well. It will be difficult to bisect, because it doesn't reproduce every time.

What I observed so far:

- When you type the password and the screen says "verifying", the desktop is really unlocked. You can't see it, but whatever you type is propagated to the desktop. So I am able to blindly switch between workspaces and close all the apps, for example. I also tried to execute `killall i3lock`, it had no effect.
- This happens both if I lock+suspend and if I simply lock the screen.
- Looks like time has to pass before this issue appears. This is unconfirmed, but looks like I can lock and unlock now and nothing bad will happen, but if I lock it and go for a coffee, after coming back I'll be stuck with "verifying".

My command is: `i3lock -efnc 000000`

**Comment by Airblader** [comment] 2017-06-13 08:05
Can you check whether i3lock is even still running (`pgrep i3lock`)? If so, what if you `xkill` i3lock (since the mouse is functioning again)?

Are you using a compositor? If so, does the issue also occur when the compositor isn't running?

**Comment by maximbaz** [comment] 2017-06-13 08:36
`pgrep` says i3lock is not running, that explains why `killall i3lock` does nothing 🙂
I'll try to repro it without compton next, although compton was not upgraded for long time.

Then I'll try to use i3lock v2.8, to confirm that the new version is indeed the root cause.

**Comment by maximbaz** [comment] 2017-06-13 11:34
It seems to work fine with compton disabled. Reading other open issues, seems to be caused by #96, which hopefully gets improved / reverted soon. Until then, this is a valid workaround:

    killall compton
    i3lock -efnc 000000
    compton &!

**Comment by Airblader** [comment] 2017-06-13 11:35
Thanks for the feedback. Closing since we don't support compositing and there's a discussion to revert #96 already.

**Closed by Airblader** 2017-06-13 11:35 UTC

**Comment by d3banjan** [comment] 2018-03-23 13:21
I seem to have the same problem.
Verify takes too long.  I am on ubuntu 17.10.
```
i3lock --debug 
[i3lock-debug] device = 3
[i3lock-debug] found Xinerama screen: 1366 x 768 at 0 x 0
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] device = 3
[i3lock-debug] Watching window 0x02400003
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 0)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
xxxx@xxxxx-xxxx-xxxx:~$ [i3lock-debug] process_xkb_event for device 3
[i3lock-debug] current password = x
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] process_xkb_event for device 3
[i3lock-debug] current password = xx
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] current password = xxx
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] current password = xxxx
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 1)
[i3lock-debug] scaling_factor is 1, physical diameter is 190 px
[i3lock-debug] successfully authenticated
[i3lock-debug] Read event of type 18
[i3lock-debug] UnmapNotify for 0x02400003
```
