### ISSUE TITLE
Setting the background to a 16bpc PNG image doesn't work

### ISSUE THREAD

**Issue by SapuSeven** [i3/i3lock#297] opened 2021-03-03 22:42 UTC
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Setting the background image to a 16bpc PNG doesn't show the image.

## Expected Behavior

Correctly show 16 bit per channel PNG background images.

## Reproduction Instructions

Export any PNG image (e.g. GIMP) with 16bpc RGB color depth (here `img.png`)
Running the `file` command will show something like the following:
<pre>
img.png: PNG image data, 1920 x 1080, 16-bit/color RGB, non-interlaced
</pre>

Now run `i3lock` with the `-i` flag:
<pre>
i3lock -i img.png
</pre>

i3lock shows a blank white screen instead of the image.

The same scenario with an 8 bit PNG works as intended.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.13
</pre>

**Comment by stapelberg** [comment] 2021-03-04 07:58
My first guess is that this might be a cairo bug/limitation instead, unless there’s any evidence that i3lock is using cairo wrong to load images…?

**Comment by SirWrexes** [comment] 2021-03-05 13:11
This is a duplicate of #244 and it's a Cairo bug.

**Closed** 2021-03-05 13:17 UTC

**Comment by SapuSeven** [comment] 2021-03-05 13:26
You're right. Thanks!
